name: build

on: workflow_dispatch

jobs:

  release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - jep-jar-release-url: "https://github.com/ninia/jep/releases/download/v4.2.0/jep-4.2.0.jar"
            ghidra-release-url: "https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_11.2.1_build/ghidra_11.2.1_PUBLIC_20241105.zip"
    steps:
    - name: Checkout Ghidrathon
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: "21"
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: "8.5"
    - name: Configure temp folder
      run: mkdir ../tmp
    - name: Download Ghidra
      run: |
        wget ${{ matrix.ghidra-release-url }} -O ../tmp/ghidra.zip
        unzip ../tmp/ghidra.zip -d ../tmp/ghidra
        mv ../tmp/ghidra/$(ls ../tmp/ghidra) ../tmp/ghidra/ghidra_PUBLIC
    - name: Download Jep
      run: wget ${{ matrix.jep-jar-release-url }} -O ./lib/jep-4.2.0.jar
    - name: Set zip name
      run: echo "zip_name=Ghidrathon-test.zip" >> $GITHUB_ENV
    - name: Build Ghidrathon
      run: gradle -PGHIDRA_INSTALL_DIR=${{ github.workspace }}/../tmp/ghidra/ghidra_PUBLIC
    - name: Configure and zip
      run: |
        mv ./dist/$(ls ./dist) ./${{ env.zip_name }}
    - name: Upload ${{ env.zip_name }} to GH Release
      uses: svenstaro/upload-release-action@2728235f7dc9ff598bd86ce3c274b74f802d2208 # v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN}}
        file: ${{ env.zip_name }}
        tag: ${{ github.ref }}
